version: "3.8"

services:
  # Product Service DB
  product-db:
    image: postgres:15
    container_name: product-db
    environment:
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_pass
      POSTGRES_DB: products_db
    ports:
      - "5433:5432"
    volumes:
      - product-db-data:/var/lib/postgresql/data

  # Order Service DB
  order-db:
    image: postgres:15
    container_name: order-db
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
      POSTGRES_DB: orders_db
    ports:
      - "5434:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data

  # Redis
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672" # management UI

  # # Product Service
  # product-service:
  #   build:
  #     context: ./product-service
  #   container_name: product-service
  #   depends_on:
  #     - product-db
  #     - redis
  #     - rabbitmq
  #   environment:
  #     PORT: 3001
  #     DB_HOST: product-db
  #     DB_PORT: 5432
  #     DB_USER: product_user
  #     DB_PASSWORD: product_pass
  #     DB_NAME: products_db
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #     RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/

  # # Order Service
  # order-service:
  #   build:
  #     context: ./order-service
  #   container_name: order-service
  #   depends_on:
  #     - order-db
  #     - redis
  #     - rabbitmq
  #     - product-service
  #   environment:
  #     PORT: 3002
  #     DB_HOST: order-db
  #     DB_PORT: 5432
  #     DB_USER: order_user
  #     DB_PASSWORD: order_pass
  #     DB_NAME: orders_db
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #     RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
  #     PRODUCT_SERVICE_URL: http://product-service:3001

volumes:
  product-db-data:
  order-db-data:
